## Alcohol Consumption Rate

In [7]:
import pandas as pd

In [9]:
# model = "Alcohol"
model = pd.read_csv(r"c:\Users\RICHMAN\Desktop\Dayta Analysis_Projects\dbms\alcohol-available-for-consumption-year-ended-december-2024.csv")

In [10]:
model

,Unnamed: 0,Unnamed: 1,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,1935,Dec,ALCA.S1,1935.12,51.100000,FINAL,Litres,6,Alcohol Available for Consumption - ALC,(DISC) Volume & Volume Per Head,Beer,NaN,NaN,NaN,NaN
1,1936,Dec,ALCA.S1,1936.12,58.700000,FINAL,Litres,6,Alcohol Available for Consumption - ALC,(DISC) Volume & Volume Per Head,Beer,NaN,NaN,NaN,NaN
2,1937,Dec,ALCA.S1,1937.12,68.700000,FINAL,Litres,6,Alcohol Available for Consumption - ALC,(DISC) Volume & Volume Per Head,Beer,NaN,NaN,NaN,NaN
3,1938,Dec,ALCA.S1,1938.12,78.100000,FINAL,Litres,6,Alcohol Available for Consumption - ALC,(DISC) Volume & Volume Per Head,Beer,NaN,NaN,NaN,NaN
4,1939,Dec,ALCA.S1,1939.12,79.200000,FINAL,Litres,6,Alcohol Available for Consumption - ALC,(DISC) Volume & Volume Per Head,Beer,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14111,2023,Dec,ALCQ.SAZZ,2023.12,138.291331,FINAL,Litres,6,Alcohol Available for Consumption - ALC,Litres of Beverage,Total all beverages,NaN,NaN,NaN,NaN
14112,2024,Mar,ALCQ.SAZZ,2024.03,111.690091,FINAL,Litres,6,Alcohol Available for Consumption - ALC,Litres of Beverage,Total all beverages,NaN,NaN,NaN,NaN
14113,2024,Jun,ALCQ.SAZZ,2024.06,104.757144,FINAL,Litres,6,Alcohol Available for Consumption - ALC,Litres of Beverage,Total all beverages,NaN,NaN,NaN,NaN
14114,2024,Sep,ALCQ.SAZZ,2024.09,109.401595,FINAL,Litres,6,Alcohol Available for Consumption - ALC,Litres of Beverage,Total all beverages,NaN,NaN,NaN,NaN
14115,2024,Dec,ALCQ.SAZZ,2024.12,156.444269,PROVISIONAL,Litres,6,Alcohol Available for Consumption - ALC,Litres of Beverage,Total all beverages,NaN,NaN,NaN,NaN

In [14]:
model.isnull()

,Unnamed: 0,Unnamed: 1,Series_reference,Period,Data_value,STATUS,UNITS,MAGNTUDE,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14111,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
14112,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
14113,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
14114,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True
14115,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True

In [15]:
model.isnull().sum()

Unnamed: 0              0
Unnamed: 1              0
Series_reference        0
Period                  0
Data_value              5
STATUS                  0
UNITS                   0
MAGNTUDE                0
Subject                 0
Group                   0
Series_title_1          0
Series_title_2      14116
Series_title_3      14116
Series_title_4      14116
Series_title_5      14116
dtype: int64

In [17]:
# model.fillna()

In [19]:
# model.duplicate().sum()

In [ ]:
# model.drop-duplicates()

NameError: name 'duplicates' is not defined